### ISSUE TITLE
Update multiple subdomains simultaneously 

### ISSUE THREAD

**Issue by discojon** [juusujanar/cloudflare-ddns#7]
Is there a way to update multiple subdomains with one instance of the container running?  I'd prefer not to have to have multiple containers if possible.

**Comment by juusujanar** [comment]
Hi, thanks for the idea.
I can try implementing that, just need to figure out a good way to work with 1 to n domains.

Can't give any timeframe at the moment though, but I'm open to pull requests.

**Comment by UncleTallest** [comment]
Looking into finishing this up later today and sending you a pull request.

**Comment by juusujanar** [comment]
@schade Hey, thanks for the help. How's the progress?

**Comment by UncleTallest** [comment]
Sorry, life intruded on me before I finished. Will update after work today
when I can look at where I am on that PR.

**Comment by juusujanar** [comment]
Completed in release 2.0 (along with rewrite to Golang).
