### ISSUE TITLE
Customizable TTL

### ISSUE THREAD

**Issue by jbrown705** [juusujanar/cloudflare-ddns#8]
Can you update the code to put a variable in for TTL so that it can be set and isn't always 1 hour by default? I prefer to leave mine set to the value of 1 for automatic.

**Comment by juusujanar** [comment]
Hi. Sorry for late reply, can be done. Will try to do it this week.

**Comment by juusujanar** [comment]
@jbrown705 Done in commit https://github.com/juusujanar/cloudflare-ddns/commit/3025f5c9c882e5bd85f0ddcc1ae0ec130b7b8a8b

Pushed 1.2 to Docker Hub. If any issues arise, let me know.

**Comment by juusujanar** [comment]
Completed in release 2.0.
